---
title: "Proposal of Final Research Project"
output: pdf_document
bibliography:
    - Literature.bib
---
*provided by Mueller, Lukas & Limberg, Daniel*

In the following we propose the topic for our Final Research Project for the Collaborative Social Science class `16 at the HSoG. We are interested in the question to which extend GDP developments of a country influence the according National Stock Indices (National Indices in the following).

# Research Question and Hypothesis

+ HO:
+ H1: 

# Research Interest and Background

# Data Sources

# Draft Literature Review

We would like to provide a two-step Literature Review. In the first part we summarize general findings of the field regarding National Indices: What are determinants that ought to be influential on the level of National Indices?
In the second, more narrow step, we focus on the relationsship between GDP developments and National Indices: Did previous studies find a relationship after all? If yes, how sure can we be about possible causation assumptions?

## National Indices

Dimson et al. provide a solid and helpful introduction ^[The work of Dimson et al. was regularly updated. The 2009 edition is the most recent version available] to world's stock markets and the question of returns [@dimson2009triumph].

The field provides a tremendous amount of research on the question what influences Stock Markets in general and National Indices in specific.
Work includes research on herding effects in advanced [@chiang2010empirical], Chinese [@tan2008herding] or Japanese Stock Markets [@chang2006idiosyncratic]. Other scholars aim to predict the direction of stock market indices via neural networks - as an attempt to go beyond traditional (non-)linear models. Examples of this stream of research are the work of Guresen et al. [@guresen2011using] or a study on the Istanbul Stock Exchange Index [@kara2011predicting]. Other authors investigate about the role of the media on stock markets [@tetlock2007giving] or even the weather [@symeonidis2010does, @kang2010weather, @yoon2009weather, @goetzmann2005rain, @cao2005stock].

Contagion and spill-over effects are also of interest for the field. Boyer et al. provide empirical evidence that stock market crises are spread globally through asset holdings of international investors. The more open (i.e. accessible) the stock markets, the higher the co-movement they conclude [@boyer2006crises]. Kenourgios et al. also investigate on these effects [@kenourgios2011financial]. Also, the field moved on to insights from behavioral economics. Bollen et al. provide an interesting piece of work and find correlations between what they call the *twitter mood* and the Dow Jones Industrial Average over time [@bollen2011twitter]. The work of Zhang et al. [@zhang2011predicting] and Si et al. [@si2013exploiting] follow a very similar approach.

## GDP Development and National Indices

The field provides various studies investigating on the relationship between GDP (or macroeconomic determinants in general) and Stock Markets in general.

For example, Claessens et al. "study how local stock market development and internationalization–listing, trading, and capital raising in international exchanges–are related to economic fundamentals" [@claessens2006stock]. Duca states that there is a clear co-movement between stock market prices and GDP in developed economies. Investigating on the causal effects he finds that "the level of economic activity in a country can potentially depend on the stock market amongst other variables"[@duca2007relationship]. On the other hand, Ritter finds that cross-country correlation of real stock returns and per capita GDP growth over 1900-2002 is negative which is mainly traced back to the fact that increases in capital and labor inputs (i.e. two main determinants of economic growth) in new corporations (i.e. representing innovation) do not necessarily imply higher dividends [@ritter2005economic].

Additionally, various studies examine the role of macroeconomic determinants on National Indices - which is also the interest of our Final Research Project.

For 42 emerging markets Yartey examines on institutional and macroeconomic determinants on stock market developments [@yartey2008determinants]. Similar studies investigate on these determinants for a wide range of countries. These include OECD countries like Belgium [@van2006stock], France [@sraer2007performance], Germany [@antonios2010stock] or New Zealand from 1990 to 2003 [@diebold2008macroeconomic]. And developing markets such as Malaysia [@rahman2009macroeconomic] or BRICS-countries like India [@singh2010causal, @agrawalla2007causality] and South Africa [@hsing2011stock] in general. 

# Reference